"""
Render the README results tables from results/metrics.json.

The README's numbers are generated, never typed. Run this after a backtest and
paste (or pipe) the output into README.md between the RESULTS markers.

    python tools/render_readme_table.py --write
"""

import argparse
import json
import os
import re
from typing import Any, Dict, Optional

RESULTS_DIR = 'results'
START_MARKER = '<!-- RESULTS:START -->'
END_MARKER = '<!-- RESULTS:END -->'
LIVE_START_MARKER = '<!-- LIVE:START -->'
LIVE_END_MARKER = '<!-- LIVE:END -->'


def _interval_label(periods_per_year: float) -> str:
    """Human name for a bar interval, derived from the annualization factor."""
    minutes = (365 * 24 * 60) / periods_per_year
    for cutoff, label in ((1.5, '1-minute'), (7.5, '5-minute'), (20, '15-minute'),
                          (75, '1-hour'), (300, '4-hour'), (1500, 'daily')):
        if minutes <= cutoff:
            return label
    return f"{minutes:.0f}-minute"


def _pct(value: Optional[float], digits: int = 2) -> str:
    if value is None:
        return 'n/a'
    return f"{value * 100:.{digits}f}%"


def _num(value: Optional[float], digits: int = 2) -> str:
    if value is None:
        return 'n/a'
    return f"{value:.{digits}f}"


def render(metrics: Dict[str, Any], meta: Dict[str, Any]) -> str:
    agent = metrics['rl_agent']

    lines = [
        f"_Generated by `backtest.py` on {meta['generated_at']}"
        f"{' (commit ' + meta['git_sha'][:8] + ')' if meta.get('git_sha') else ''}._",
        "",
        f"**Protocol:** walk-forward, {len(meta.get('folds', []))} folds. Each fold trains only on "
        f"bars preceding its test window, with a {meta.get('purge_bars', 60)}-bar purge gap between "
        "them; the reported curve is the concatenation of the untouched test segments.",
        "",
        f"**Data:** {meta.get('data_path', 'the dataset')} — {meta['data_rows']:,} "
        f"{_interval_label(meta['periods_per_year'])} bars, "
        f"{meta['data_start'][:10]} to {meta['data_end'][:10]}. "
        f"Out-of-sample span: {meta['oos_start'][:10]} to {meta['oos_end'][:10]}.",
        "",
        f"**Execution:** {meta.get('execution_mode', 'taker')} — "
        f"{meta.get('fee_per_fill', meta.get('transaction_cost', 0)) * 100:.3f}% fee per fill"
        + (f" plus {meta['slippage'] * 100:.3f}% slippage" if meta.get('slippage') else
           " and no slippage (a resting limit fills at its own price)")
        + f", charged on entry and exit. Agent variant `{meta['variant']}`, "
          f"seed {meta.get('seed')}.",
        "",
        "### Out-of-sample results",
        "",
        "| Metric | RL Agent |",
        "|---|---|",
        f"| Total Return | {_pct(agent['total_return'])} |",
        f"| Annualized Return | {_pct(agent['annualized_return'])} |",
        f"| Sharpe Ratio | {_num(agent['sharpe_ratio'])} |",
        f"| Sortino Ratio | {_num(agent['sortino_ratio'])} |",
        f"| Max Drawdown | {_pct(agent['max_drawdown'])} |",
        f"| Calmar Ratio | {_num(agent['calmar_ratio'])} |",
        f"| Round Trips | {agent.get('total_trades', 0):,} |",
        f"| Win Rate | {_pct(agent.get('win_rate'), 1)} |",
        f"| Profit Factor | {_num(agent.get('profit_factor'))} |",
        "",
        "### Comparison with benchmarks",
        "",
        "| Strategy | Return | Annualized | Sharpe | Max DD | Calmar | Round Trips | Win Rate |",
        "|---|---|---|---|---|---|---|---|",
    ]

    labels = {
        'rl_agent': 'RL Bot',
        'buy_and_hold': 'Buy & Hold',
        'rsi_strategy': 'RSI Strategy',
    }
    for key, label in labels.items():
        row = metrics.get(key)
        if not row:
            continue
        lines.append(
            f"| {label} | {_pct(row['total_return'])} | {_pct(row['annualized_return'])} "
            f"| {_num(row['sharpe_ratio'])} | {_pct(row['max_drawdown'])} "
            f"| {_num(row['calmar_ratio'])} | {row.get('total_trades', 0):,} "
            f"| {_pct(row.get('win_rate'), 1)} |"
        )

    folds = meta.get('folds', [])
    if folds:
        lines += [
            "",
            "### Per-fold out-of-sample results",
            "",
            "| Fold | Test window | Return | Sharpe | Max DD | Round Trips | Win Rate |",
            "|---|---|---|---|---|---|---|",
        ]
        for fold in folds:
            lines.append(
                f"| {fold['fold']} | {fold['test_start'][:10]} → {fold['test_end'][:10]} "
                f"| {_pct(fold['total_return'])} | {_num(fold['sharpe_ratio'])} "
                f"| {_pct(fold['max_drawdown'])} | {fold['total_trades']:,} "
                f"| {_pct(fold['win_rate'], 1)} |"
            )

    return "\n".join(lines)


def render_live(status: Dict[str, Any]) -> str:
    """Render the live paper account block from results/live/status.json."""
    learning = status.get('online_learning', {})
    benchmark = status.get('buy_hold_return_since_start')
    delta = (status['total_return'] - benchmark) if benchmark is not None else None

    lines = [
        f"_Snapshot of `results/live/status.json`, updated {status['updated_at']}._",
        "",
        f"Paper account trading **{status['symbol']} {status['interval']}** bars from "
        f"`{status['source']}`, model origin `{status['model_origin']}`. "
        f"Last bar {status['last_bar']} at {_money(status['last_price'])}.",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Equity | {_money(status['equity'])} |",
        f"| Total return | {_pct(status['total_return'])} |",
        f"| Buy & hold, same window | {_pct(benchmark)} |",
        f"| Difference | {_pct(delta)} |",
        f"| Round trips | {status['round_trips']} |",
        f"| Win rate | {_pct(status['win_rate'], 1)} |",
        f"| Max drawdown so far | {_pct(status['drawdown'])} |",
        f"| Position | "
        f"{('%.6f BTC' % status['btc_held']) if status['btc_held'] else 'flat'} |",
        f"| Halted | {status['halted']} |",
        f"| Online-learning cycles | {learning.get('cycles', 0)} "
        f"({learning.get('promotions', 0)} promoted) |",
    ]
    return "\n".join(lines)


def _money(value: Optional[float]) -> str:
    if value is None:
        return 'n/a'
    return f"${value:,.2f}"


def _replace_block(text: str, start: str, end: str, body: str) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"README has no {start} / {end} block")
    return re.sub(
        re.escape(start) + r".*?" + re.escape(end),
        f"{start}\n{body}\n{end}",
        text,
        flags=re.DOTALL,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--results-dir', default=RESULTS_DIR)
    parser.add_argument('--readme', default='README.md')
    parser.add_argument('--write', action='store_true',
                        help='Replace the RESULTS block in README.md in place')
    args = parser.parse_args()

    with open(os.path.join(args.results_dir, 'metrics.json')) as file:
        metrics = json.load(file)
    with open(os.path.join(args.results_dir, 'run_meta.json')) as file:
        meta = json.load(file)

    table = render(metrics, meta)

    live_table = None
    live_status_path = os.path.join(args.results_dir, 'live', 'status.json')
    if os.path.exists(live_status_path):
        with open(live_status_path) as file:
            live_table = render_live(json.load(file))

    if not args.write:
        print(table)
        if live_table:
            print('\n' + live_table)
        return

    with open(args.readme) as file:
        readme = file.read()

    updated = _replace_block(readme, START_MARKER, END_MARKER, table)
    if live_table:
        updated = _replace_block(updated, LIVE_START_MARKER, LIVE_END_MARKER, live_table)

    with open(args.readme, 'w') as file:
        file.write(updated)

    print(f"Updated the results block{' and live block' if live_table else ''} in {args.readme}")


if __name__ == "__main__":
    main()
